language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_install:
  - npm install -g bower
  - bower install
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
